/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIdeaIdIndexRouteImport } from './routes/ideas/$ideaId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdIndexRoute = IdeasIdeaIdIndexRouteImport.update({
  id: '/ideas/$ideaId/',
  path: '/ideas/$ideaId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas/$ideaId/': typeof IdeasIdeaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas/$ideaId/': typeof IdeasIdeaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ideas/$ideaId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ideas/$ideaId'
  id: '__root__' | '/' | '/ideas/$ideaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasIdeaIdIndexRoute: typeof IdeasIdeaIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId/': {
      id: '/ideas/$ideaId/'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId/'
      preLoaderRoute: typeof IdeasIdeaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasIdeaIdIndexRoute: IdeasIdeaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
